### ISSUE TITLE
add commenting ability

### ISSUE THREAD

**Issue by bernardjhuang** [bernardjhuang/gamerunnersnews#1]

**Comment by hangsu** [comment]
this is _really_ tough. 

There's no good commenting system. Disqus sucks, and no lol player would have a disqus account anyways. Also, they show ads in ur comments.

And we need some sort of account to be associated with comments or else we will probably have a wall of viagra-related comments.

I guess facebook comments is an option

**Comment by bernardjhuang** [comment]
yeah, looking into fb comments but this isn't high priority right now.
